#!/bin/bash

source .direnv/python-3.8.9/bin/activate
source .vars

param="${1:-"c-hello.py"}"

case $param in
  c-sync-assets.py)
    ./pytrade assets
    ;;
  c-sync-etfholdings.py)
    ./pytrade etfholdings
    ;;
  c-sync-prices.py)
    ./pytrade bars
    ;;
  *)
    python $param
    ;;
esac
