#!/usr/bin/env python
# -*- coding: utf-8 -*-

from cmd.backtest import main as backtest_cmd
from cmd.backtest import argparser as backtest_args
from cmd.bars import main as bars_cmd
from cmd.bars import argparser as bars_args
from cmd.crontab import main as crontab_cmd
from cmd.crontab import argparser as crontab_args
from cmd.download import main as download_cmd
from cmd.download import argparser as download_args
from cmd.screener import main as screener_cmd
from cmd.screener import argparser as screener_args
from cmd.stream import main as stream_cmd
from cmd.stream import argparser as stream_args
from cmd.sync import main as sync_cmd
from cmd.sync import argparser as sync_args
from cmd.version import main as version_cmd
from cmd.version import argparser as version_args
import pytrader as pt
from pytrader.log import logger
import traceback


"""
  pytrade
  ------
  a cli interface to pytrader
"""


def main(args):
  try:
    subcommands = {
      'crontab' : crontab_cmd,
      'backtest' : backtest_cmd,
      'bars' : bars_cmd,
      'download' : download_cmd,
      'screener' : screener_cmd,
      'stream' : stream_cmd,
      'sync' : sync_cmd,
      'version' : version_cmd,
    }
    subcommands[args.subcommand](args)

  except Exception as e:
    logger.error(e)
    print(e)
    print(traceback.format_exc())


if __name__ == '__main__':
  parser = pt.ArgumentParser()
  parser.add_argument("-v", "--verbose", action='store_true', help="verbose")

  subparsers = parser.add_subparsers(dest="subcommand") # this line changed
  subparsers.required = True

  backtest_args(subparsers)
  bars_args(subparsers)
  crontab_args(subparsers)
  download_args(subparsers)
  screener_args(subparsers)
  stream_args(subparsers)
  sync_args(subparsers)
  version_args(subparsers)

  args = parser.parse_args()

  timer = pt.Timer()
  logger.info('pytrader cli tool')
  main(args)
  timer.report()
